version: '3.8'

services:
  frontend:
    build: ./bank-frontend
    ports:
      - "5173:5173"
    networks:
      - app-network
    command: npm run dev


  backend:
    build: ./bank-backend
    ports:
      - "8000:80"
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mybank
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network
      
  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8087:80"
    environment:
      PMA_HOST: db
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:

volumes:
  dbdata:
