<?php

namespace ContainerI9AYoqo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GZ8xLkzService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.GZ8xLkz' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.GZ8xLkz'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'categoryRepository' => ['privates', 'App\\Repository\\CategoryRepository', 'getCategoryRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'expense' => ['privates', '.errored..service_locator.GZ8xLkz.App\\Entity\\Expense', NULL, 'Cannot autowire service ".service_locator.GZ8xLkz": it references class "App\\Entity\\Expense" but no such service exists.'],
        ], [
            'categoryRepository' => 'App\\Repository\\CategoryRepository',
            'em' => '?',
            'expense' => 'App\\Entity\\Expense',
        ]);
    }
}
