<?php

namespace ContainerI9AYoqo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExpenseService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.BWLti1t.App\Entity\Expense' shared service.
     *
     * @return \App\Entity\Expense
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.BWLti1t": it references class "App\\Entity\\Expense" but no such service exists.');
    }
}
