<?php

namespace ContainerOmaIbzw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_R3QIa2EService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.R3QIa2E' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.R3QIa2E'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'expense' => ['privates', '.errored..service_locator.R3QIa2E.App\\Entity\\Expense', NULL, 'Cannot autowire service ".service_locator.R3QIa2E": it references class "App\\Entity\\Expense" but no such service exists.'],
        ], [
            'em' => '?',
            'expense' => 'App\\Entity\\Expense',
        ]);
    }
}
