<?php

namespace ContainerOmaIbzw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExpense2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.R3QIa2E.App\Entity\Expense' shared service.
     *
     * @return \App\Entity\Expense
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.R3QIa2E": it references class "App\\Entity\\Expense" but no such service exists.');
    }
}
