<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerI9AYoqo\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerI9AYoqo/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerI9AYoqo.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerI9AYoqo\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerI9AYoqo\App_KernelDevDebugContainer([
    'container.build_hash' => 'I9AYoqo',
    'container.build_id' => 'e4556fbf',
    'container.build_time' => 1746435754,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerI9AYoqo');
