<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZxLE6xU\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZxLE6xU/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZxLE6xU.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZxLE6xU\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZxLE6xU\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZxLE6xU',
    'container.build_id' => 'f398a944',
    'container.build_time' => 1754430581,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZxLE6xU');
