<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZJkq2ys\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZJkq2ys/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZJkq2ys.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZJkq2ys\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZJkq2ys\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZJkq2ys',
    'container.build_id' => '69d48f0f',
    'container.build_time' => 1749729704,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZJkq2ys');
