nelmio_cors:
    defaults:
        allow_origin: ['http://localhost:3000'] # або '*', якщо в розробці
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Content-Type']
        max_age: 3600
    paths:
        '^/api/':
            allow_origin: ['http://localhost:3000']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
            allow_headers: ['Content-Type', 'Authorization']
            expose_headers: ['Content-Type']
            max_age: 3600
