services:
    # Alias interfaces to concrete services for testing
    Doctrine\ORM\EntityManagerInterface:
        alias: 'doctrine.orm.default_entity_manager'
        public: true
        
    Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface:
        alias: 'security.user_password_hasher'
        public: true
