services:
    # Make services public for testing
    Doctrine\ORM\EntityManagerInterface:
        public: true
        
    Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface:
        public: true
