services:
    # Make services public for testing
    _defaults:
        public: true
        
    # Explicitly make these services public for tests
    Doctrine\ORM\EntityManagerInterface:
        alias: 'doctrine.orm.entity_manager'
        public: true
        
    Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface:
        alias: 'security.user_password_hasher'
        public: true
        
    doctrine.orm.entity_manager:
        public: true
        
    security.user_password_hasher:
        public: true
